const SET_PROGRESS = 'SET_PROGRESS'

const PROMISE_PENDING = 'PROMISE_PENDING'
const PROMISE_SUCCESS = 'PROMISE_SUCCESS'
const PROMISE_FAILURE = 'PROMISE_FAILURE'

const ADD_TOAST = 'ADD_TOAST'
const DELETE_TOAST = 'DELETE_TOAST'

const SET_ENV = 'SET_ENV'
const ENV_KEY = 'ENV_KEY'

const SET_ENV_I18N = 'SET_ENV_I18N'

export default { 
    PROMISE_PENDING, 
    PROMISE_SUCCESS, 
    PROMISE_FAILURE, 
    SET_PROGRESS, 
    ADD_TOAST, 
    DELETE_TOAST,
    SET_ENV,
    ENV_KEY,
    SET_ENV_I18N
}

